"""add analysis sessions

Revision ID: de1a9b583fe4
Revises: 46be3fd3c90c
Create Date: 2026-05-15 05:38:07.502027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1a9b583fe4'
down_revision: Union[str, Sequence[str], None] = '46be3fd3c90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('current_topic', sa.String(length=255), nullable=True),
    sa.Column('current_intent', sa.String(length=255), nullable=True),
    sa.Column('current_filters_json', sa.JSON(), nullable=True),
    sa.Column('last_result_summary_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_sessions_dataset_id'), 'analysis_sessions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_analysis_sessions_id'), 'analysis_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_sessions_user_id'), 'analysis_sessions', ['user_id'], unique=False)
    op.create_table('analysis_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_messages_id'), 'analysis_messages', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_messages_session_id'), 'analysis_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_messages_session_id'), table_name='analysis_messages')
    op.drop_index(op.f('ix_analysis_messages_id'), table_name='analysis_messages')
    op.drop_table('analysis_messages')
    op.drop_index(op.f('ix_analysis_sessions_user_id'), table_name='analysis_sessions')
    op.drop_index(op.f('ix_analysis_sessions_id'), table_name='analysis_sessions')
    op.drop_index(op.f('ix_analysis_sessions_dataset_id'), table_name='analysis_sessions')
    op.drop_table('analysis_sessions')
    # ### end Alembic commands ###
